development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:7adb7d1d38ad5467a1be33e39394294c@soapfish.redistogo.com:11783/
  channel_prefix: hoiioh_production
