meta_product_name: "HOIIOH"
meta_title: "HOIIOH - Instant Volunteering"
meta_description: "HOIIOH is a location-based app that helps you find volunteering opportunities on the go"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
